import { useEffect, useRef, useState } from 'react'
import { ArrowDown, Bell, Check, FolderOpen, Maximize2, MousePointer2, Music2, Pause, Play, Volume2, X } from 'lucide-react'
import type { RuntimeState } from '../lib/runtime'

const WINDOWS=['Workspace','Media player','Presentation']
const ITEMS=['Design brief','Sprint notes','GestureCommand','Camera test','Profile library','Release checklist','Quick ideas','Saved recording']
export function RuntimeWorkspace({state,armed,onArm,onAction}:{state:RuntimeState;armed:boolean;onArm:()=>void;onAction:(action:'left-click'|'right-click'|'double-click'|'scroll-up'|'scroll-down'|'volume-up'|'volume-down'|'next-window'|'previous-window'|'escape'|'play-pause')=>void}){
  const [seconds,setSeconds]=useState(0),beepRef=useRef<AudioContext|null>(null)
  useEffect(()=>{if(!state.playing)return;const timer=window.setInterval(()=>setSeconds(value=>(value+1)%180),1000);return()=>window.clearInterval(timer)},[state.playing])
  useEffect(()=>{if(state.pulse===0||state.lastAction!=='play pause')return;try{const audio=beepRef.current??new AudioContext();beepRef.current=audio;const oscillator=audio.createOscillator(),gain=audio.createGain();oscillator.frequency.value=440;gain.gain.value=state.volume/4000;oscillator.connect(gain).connect(audio.destination);oscillator.start();oscillator.stop(audio.currentTime+.13)}catch{/* Audio may be blocked until interaction. */}},[state.pulse,state.lastAction,state.volume])
  useEffect(()=>()=>{void beepRef.current?.close()},[])
  return <section className="gc-runtime gc-card" aria-label="Live action test workspace"><div className="gc-runtime-head"><div><span className="gc-kicker">INTERACTIVE TEST WORKSPACE</span><h2>See your actions happen.</h2><p>Arm this workspace, then make a gesture or use the test buttons. This is an interactive preview, not OS control.</p></div><button className={`gc-button ${armed?'danger':''}`} onClick={onArm}>{armed?<><Pause size={15}/>Pause preview</>:<><Play size={15}/>Arm preview</>}</button></div>
    <div className="gc-runtime-body"><div className="gc-runtime-stage"><div className="gc-runtime-windowbar"><span className="gc-dots"><i/><i/><i/></span><strong>{WINDOWS[state.window]}</strong><span><Maximize2 size={13}/></span></div>
      {state.window===0?<div className="gc-runtime-work"><div className="gc-runtime-workhead"><FolderOpen size={17}/><strong>My workspace</strong><span>{state.clicks} clicks · {state.doubleClicks} double clicks</span></div><div className="gc-runtime-files">{ITEMS.slice(state.scroll,state.scroll+3).map((item,index)=><button key={item} className={state.selected===index?'selected':''} onClick={()=>onAction('left-click')}><span>{['📁','📄','✦'][index%3]}</span><strong>{item}</strong><small>{index===state.selected?'Selected':'Click to select'}</small></button>)}</div><div className="gc-runtime-scroll"><button onClick={()=>onAction('scroll-up')}>↑</button><span>Row {state.scroll+1}–{Math.min(state.scroll+3,ITEMS.length)} of {ITEMS.length}</span><button onClick={()=>onAction('scroll-down')}>↓</button></div></div>:state.window===1?<div className="gc-runtime-media"><div className="gc-record"><Music2 size={45}/></div><strong>Gesture Flow</strong><span>Ambient test track · local preview</span><button onClick={()=>onAction('play-pause')}>{state.playing?<Pause size={19}/>:<Play size={19}/>}</button><div className="gc-track"><i style={{width:`${seconds/180*100}%`}}/></div><small>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')} / 3:00</small></div>:<div className="gc-runtime-presentation"><span>03 / 08</span><strong>Control your workflow<br/>with a gesture.</strong><p>Window switching brings this presentation into focus.</p><div>GESTURECOMMAND</div></div>}
      {state.detailOpen&&<div className="gc-runtime-dialog"><button onClick={()=>onAction('escape')} aria-label="Close detail"><X size={15}/></button><FolderOpen size={29}/><strong>Item opened</strong><span>Double click opened a detail window. Use Escape to close it.</span></div>}
      {state.contextOpen&&<div className="gc-runtime-context"><strong>Context menu</strong><button onClick={()=>onAction('left-click')}><Check size={13}/>Select item</button><button onClick={()=>onAction('escape')}><X size={13}/>Close menu</button></div>}
      <div className="gc-runtime-pointer" style={{left:`${state.cursor.x*100}%`,top:`${state.cursor.y*100}%`}}><MousePointer2 size={24} fill="#49d8ed"/><span key={state.pulse} className="gc-runtime-ripple"/></div></div>
      <div className="gc-runtime-panel"><div className="gc-runtime-feedback"><span><Bell size={16}/>LATEST RESULT</span><strong>{state.lastAction}</strong><small>{state.pulse?`Action ${state.pulse} executed in this workspace`:'Waiting for a gesture or test click'}</small></div><div className="gc-runtime-volume"><span><Volume2 size={16}/>Volume</span><strong>{state.volume}%</strong><div><i style={{width:`${state.volume}%`}}/></div></div><div className="gc-runtime-counts"><div><strong>{state.clicks}</strong><span>left clicks</span></div><div><strong>{state.rightClicks}</strong><span>right clicks</span></div><div><strong>{state.doubleClicks}</strong><span>opens</span></div></div><div className="gc-runtime-tools"><button onClick={()=>onAction('previous-window')}>← Window</button><button onClick={()=>onAction('next-window')}>Window →</button><button onClick={()=>onAction('volume-down')}>− Volume</button><button onClick={()=>onAction('volume-up')}>+ Volume</button></div><div className="gc-runtime-note"><ArrowDown size={15}/>Hand position moves the cyan cursor when preview is armed.</div></div></div>
  </section>
}
