import { useCallback, useEffect, useRef, useState } from 'react'
import { Activity, Aperture, ArrowDownToLine, BarChart3, Camera, Check, CircleHelp, Command, Crosshair, Hand, History, LayoutDashboard, LockKeyhole, Monitor, MousePointer2, Pause, Play, Plus, ScanLine, Settings2, ShieldCheck, SlidersHorizontal, Trash2, WandSparkles } from 'lucide-react'
import { useCamera } from './hooks/useCamera'
import { GestureTracker } from './lib/tracker'
import { GESTURES, CONNECTIONS } from './lib/gestures'
import { loadActions, type DesktopAction, type DesktopStatus } from './lib/desktop'
import { applyRuntimeAction, INITIAL_RUNTIME, moveRuntimePointer } from './lib/runtime'
import { RuntimeWorkspace } from './components/RuntimeWorkspace'
import type { Profile } from './lib/types'

type Tab = 'control' | 'actions' | 'calibration' | 'gestures' | 'history' | 'statistics' | 'settings'
type Log = { id: string; time: number; gesture: string; confidence: number; action: string; result: string }
type Preferences = { threshold: number; sensitivity: number; smoothing: number; cooldown: number; hands: 1 | 2; mirror: boolean; skeleton: boolean; sound: boolean; inactivity: number }
const DEFAULT_PREFERENCES: Preferences = { threshold: 75, sensitivity: 55, smoothing: 72, cooldown: 450, hands: 1, mirror: true, skeleton: true, sound: false, inactivity: 120 }
const NAV: {id: Tab;label: string;icon: typeof Activity}[] = [
  {id:'control',label:'Control center',icon:LayoutDashboard},{id:'actions',label:'Action mappings',icon:Command},
  {id:'calibration',label:'Calibration',icon:Crosshair},{id:'gestures',label:'Gesture library',icon:Hand},
  {id:'history',label:'Activity history',icon:History},{id:'statistics',label:'Statistics',icon:BarChart3},
  {id:'settings',label:'Settings',icon:Settings2},
]
const ACTIONS: {id:DesktopAction;label:string}[] = [
  {id:'none',label:'No action'},{id:'left-click',label:'Left click'},{id:'right-click',label:'Right click'},
  {id:'double-click',label:'Double click'},{id:'scroll-up',label:'Scroll up'},{id:'scroll-down',label:'Scroll down'},
  {id:'volume-up',label:'Volume up'},{id:'volume-down',label:'Volume down'},
  {id:'next-window',label:'Next window'},{id:'previous-window',label:'Previous window'},
  {id:'escape',label:'Escape key'},{id:'play-pause',label:'Play / pause media'},
]
const CAL_POINTS = [{x:.15,y:.18,label:'Top left'},{x:.85,y:.18,label:'Top right'},{x:.5,y:.5,label:'Center'},{x:.15,y:.82,label:'Bottom left'},{x:.85,y:.82,label:'Bottom right'}]
const read = <T,>(key:string,fallback:T):T => { try { const value=localStorage.getItem(`gesturecommand:${key}`); return value?JSON.parse(value) as T:fallback } catch { return fallback } }
const save = (key:string,value:unknown) => { try { localStorage.setItem(`gesturecommand:${key}`,JSON.stringify(value)) } catch { /* Storage may be disabled. */ } }
const formatTime = (time:number) => new Date(time).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})

export default function GestureCommandApp(){
  const [tab,setTab]=useState<Tab>('control')
  const [preferences,setPreferences]=useState<Preferences>(()=>({...DEFAULT_PREFERENCES,...read('preferences',{})}))
  const [mappings,setMappings]=useState<Record<string,DesktopAction>>(loadActions)
  const [profiles,setProfiles]=useState<Profile[]>(()=>read('pose-profiles',[]))
  const [logs,setLogs]=useState<Log[]>(()=>read('activity',[]))
  const [desktop,setDesktop]=useState<DesktopStatus>({armed:false,ready:false,error:''})
  const [previewArmed,setPreviewArmed]=useState(false)
  const [runtime,setRuntime]=useState(INITIAL_RUNTIME)
  const [calibrating,setCalibrating]=useState(false),[calPoint,setCalPoint]=useState(0),[calibrated,setCalibrated]=useState(()=>read('calibrated',false))
  const [toast,setToast]=useState(''),[profileName,setProfileName]=useState(''),[showGuide,setShowGuide]=useState(false)
  const camera=useCamera(profiles),tracker=useRef(new GestureTracker()),lastAction=useRef(0),lastHand=useRef(Date.now()),cursor=useRef<{x:number;y:number}|null>(null)
  const overlay=useRef<HTMLCanvasElement>(null),preferencesRef=useRef(preferences),mappingsRef=useRef(mappings),desktopRef=useRef(desktop),previewRef=useRef(previewArmed),calibrationHold=useRef(0)
  preferencesRef.current=preferences;mappingsRef.current=mappings;desktopRef.current=desktop;previewRef.current=previewArmed
  const live=camera.status==='live',starting=camera.status==='permission'||camera.status==='loading'
  const current=camera.detections.find(d=>d.id!=='unknown')??camera.detections[0]
  const actionName=(id:string)=>ACTIONS.find(a=>a.id===id)?.label??id
  const alert=useCallback((message:string)=>{setToast(message);window.setTimeout(()=>setToast(current=>current===message?'':current),4200)},[])
  const updatePreferences=<K extends keyof Preferences>(key:K,value:Preferences[K])=>setPreferences(p=>({...p,[key]:value}))
  const executePreview=useCallback((action:DesktopAction)=>{setRuntime(current=>applyRuntimeAction(current,action))},[])
  const stop=useCallback(()=>{camera.stop();tracker.current.clear();cursor.current=null;setPreviewArmed(false);void window.gestureDesktop?.arm(false)},[camera.stop])
  const start=()=>{tracker.current.clear();void camera.start(preferences.hands)}
  useEffect(()=>save('preferences',preferences),[preferences])
  useEffect(()=>save('actions',mappings),[mappings])
  useEffect(()=>save('pose-profiles',profiles),[profiles])
  useEffect(()=>save('activity',logs),[logs])
  useEffect(()=>{const api=window.gestureDesktop;if(!api)return;void api.status().then(setDesktop);return api.onStatus(setDesktop)},[])
  useEffect(()=>{if(!live&&desktop.armed)void window.gestureDesktop?.arm(false)},[live,desktop.armed])
  useEffect(()=>{
    if(!live)return
    const timer=window.setInterval(()=>{
      const now=Date.now(),frames=camera.frameRef.current,settings=preferencesRef.current
      if(frames.length)lastHand.current=now
      if((desktopRef.current.armed||previewRef.current)&&now-lastHand.current>settings.inactivity*1000){void window.gestureDesktop?.arm(false);setPreviewArmed(false);alert('Control paused: no hand detected.');return}
      for(const found of tracker.current.update(frames,settings.threshold,now)){
        const action=mappingsRef.current[found.id]??'none'
        let result='Recognized'
        if((desktopRef.current.armed||previewRef.current)&&action!=='none'&&now-lastAction.current>=settings.cooldown){
          lastAction.current=now;executePreview(action);if(desktopRef.current.armed)void window.gestureDesktop?.action(action);result=desktopRef.current.armed?'Desktop + preview action':'Preview action executed'
        }else if(action!=='none')result=desktopRef.current.armed||previewRef.current?'Cooling down':'Control paused'
        setLogs(previous=>[{id:crypto.randomUUID(),time:now,gesture:found.name,confidence:found.confidence,action:actionName(action),result},...previous].slice(0,500))
        if(settings.sound){const audio=new AudioContext(),osc=audio.createOscillator(),gain=audio.createGain();osc.connect(gain).connect(audio.destination);gain.gain.value=.03;osc.frequency.value=660;osc.start();osc.stop(audio.currentTime+.08);osc.onended=()=>void audio.close()}
      }
      const hand=frames.find(d=>d.id==='open'&&d.confidence>=settings.threshold)
      const palm=hand?.points[9]
      if((desktopRef.current.armed||previewRef.current)&&palm){
        const target={x:settings.mirror?1-palm.x:palm.x,y:palm.y}
        const alpha=Math.max(.05,1-settings.smoothing/110),prior=cursor.current
        const next=prior?{x:prior.x+(target.x-prior.x)*alpha,y:prior.y+(target.y-prior.y)*alpha}:target
        cursor.current=next;setRuntime(current=>moveRuntimePointer(current,next.x,next.y));if(desktopRef.current.armed)void window.gestureDesktop?.move(next.x,next.y)
      }
      if(calibrating&&calPoint<CAL_POINTS.length&&palm){
        const target=CAL_POINTS[calPoint],x=settings.mirror?1-palm.x:palm.x
        if(Math.hypot(target.x-x,target.y-palm.y)<.16){calibrationHold.current++;
          if(calibrationHold.current>=8){calibrationHold.current=0;if(calPoint===CAL_POINTS.length-1){setCalibrating(false);setCalibrated(true);save('calibrated',true);alert('Five-point calibration complete.')}else setCalPoint(n=>n+1)}}
        else calibrationHold.current=0
      }
    },85)
    return()=>window.clearInterval(timer)
  },[live,camera.frameRef,calibrating,calPoint,alert,executePreview])
  useEffect(()=>{
    let animation=0
    const draw=()=>{
      const canvas=overlay.current,video=camera.videoRef.current
      if(canvas&&video){const width=video.videoWidth||640,height=video.videoHeight||480
        if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height}
        const ctx=canvas.getContext('2d');if(ctx){ctx.clearRect(0,0,width,height)
          if(preferencesRef.current.skeleton)for(const hand of camera.frameRef.current){ctx.lineWidth=2;ctx.strokeStyle='#52e3e6';ctx.fillStyle='#b49bff';for(const [a,b] of CONNECTIONS){ctx.beginPath();ctx.moveTo(hand.points[a].x*width,hand.points[a].y*height);ctx.lineTo(hand.points[b].x*width,hand.points[b].y*height);ctx.stroke()}for(const point of hand.points){ctx.beginPath();ctx.arc(point.x*width,point.y*height,3,0,Math.PI*2);ctx.fill()}}}}
      animation=requestAnimationFrame(draw)
    }
    animation=requestAnimationFrame(draw);return()=>cancelAnimationFrame(animation)
  },[camera.frameRef,camera.videoRef])
  const arm=async()=>{if(!window.gestureDesktop){alert('System control is available only in the Electron desktop app.');return}const result=await window.gestureDesktop.arm(!desktop.armed);setDesktop(result);if(result.armed)alert('System control armed. Use Pause or the tray to stop.')}
  const tryAction=(action:DesktopAction)=>{if(action==='none'){alert('Choose an action for this gesture first.');return}executePreview(action);setTab('control')}
  const captureProfile=()=>{
    const descriptor=camera.descriptorRef.current
    if(!live||descriptor.length!==15){alert('Show a clear hand pose to the live camera first.');return}
    const name=profileName.trim();if(!name){alert('Enter a name for this gesture.');return}
    setProfiles(items=>[{id:`custom-${crypto.randomUUID()}`,name,descriptor:[...descriptor],createdAt:Date.now()},...items].slice(0,25));setProfileName('');alert(`Saved ${name} to your gesture library.`)
  }
  const exportData=()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),mappings,profiles,preferences,logs},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='gesturecommand-profile.json';link.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}
  const importData=(file:File)=>{void file.text().then(text=>{try{const data=JSON.parse(text);if(data.version!==1||!data.mappings||typeof data.mappings!=='object')throw Error('Invalid profile');setMappings({...loadActions(),...data.mappings});if(Array.isArray(data.profiles))setProfiles(data.profiles.slice(0,25));alert('Profile imported. Review mappings before arming control.')}catch{alert('Could not import this profile JSON.')}})}
  return <div className="gc-shell">
    <aside className="gc-sidebar"><div className="gc-logo"><span className="gc-logo-icon"><Hand size={22}/></span><div><strong>Gesture<span>Command</span></strong><small>DESKTOP CONTROL SYSTEM</small></div></div>
      <div className="gc-sidebar-label">WORKSPACE</div><nav>{NAV.map(item=><button key={item.id} className={tab===item.id?'active':''} onClick={()=>setTab(item.id)}><item.icon size={18}/>{item.label}{item.id==='history'&&logs.length>0&&<em>{logs.length}</em>}</button>)}</nav>
      <div className="gc-side-bottom"><div className="gc-safety"><ShieldCheck size={18}/><div><strong>Privacy first</strong><span>All inference stays on device</span></div></div><button onClick={()=>setShowGuide(true)}><CircleHelp size={17}/>How it works</button></div>
    </aside>
    <div className="gc-main"><header className="gc-top"><div className="gc-breadcrumb">WORKSPACE <span>/</span> {NAV.find(n=>n.id===tab)?.label.toUpperCase()}</div><div className="gc-top-right"><span className={`gc-status ${desktop.armed?'armed':''}`}><i/>{desktop.armed?'CONTROL ARMED':previewArmed?'PREVIEW ARMED':live?'CAMERA LIVE':'SYSTEM PAUSED'}</span><button className="gc-avatar" title="Local profile">GC</button></div></header>
      <main className="gc-content"><div className="gc-heading"><div><p className="gc-kicker">GESTURECOMMAND / {tab.toUpperCase()}</p><h1>{({control:'Control center',actions:'Action mappings',calibration:'Calibration',gestures:'Gesture library',history:'Activity history',statistics:'Statistics',settings:'Settings'} as Record<Tab,string>)[tab]}<span>.</span></h1><p>{({control:'Your hands are the interface. See what the camera recognizes and decide when control is active.',actions:'Choose what each recognized pose does on your computer.',calibration:'Align hand tracking with your camera position and workspace.',gestures:'Built-in poses and your own landmark-based gestures.',history:'A local record of recognized poses and actions.',statistics:'See how recognition and control perform over time.',settings:'Fine-tune recognition, cursor movement and safety.'} as Record<Tab,string>)[tab]}</p></div><div className="gc-heading-actions"><button className="gc-button secondary" onClick={()=>setTab('calibration')}><Crosshair size={16}/>Calibrate</button><button className={`gc-button ${live?'danger':''}`} onClick={live||starting?stop:start}>{live?<Pause size={16}/>:<Camera size={16}/>} {starting?'Cancel camera':live?'Stop camera':'Start camera'}</button></div></div>
      {!window.gestureDesktop&&<div className="gc-browser-banner"><Monitor size={20}/><div><strong>Browser preview</strong><span>Actions run in the interactive test workspace below. Real OS input still requires the Electron desktop app.</span></div></div>}
      {desktop.error&&<div className="gc-error" role="alert">{desktop.error}</div>}
      <div style={{display:tab==='control'?'block':'none'}}><div className="gc-hero-grid"><section className="gc-card gc-camera"><div className="gc-card-head"><span><span className="gc-live-dot"/> LIVE CAMERA</span><span>{camera.metrics.fps} FPS · {camera.metrics.runtime}</span></div><div className="gc-video-wrap"><video ref={camera.videoRef} autoPlay playsInline muted className={preferences.mirror?'mirror':''}/><canvas ref={overlay} className={preferences.mirror?'mirror':''}/>{!live&&<div className="gc-camera-placeholder"><div className="gc-hand-art"><Hand size={100} strokeWidth={1}/><span className="gc-orbit one"/><span className="gc-orbit two"/></div><h3>{starting?'Initializing hand tracking…':camera.status==='error'?'Camera unavailable':'Your control starts here'}</h3><p>{camera.status==='error'?camera.error:starting?'Allow camera access and wait for the model to load.':'Start your camera to detect gestures and view the hand skeleton.'}</p><button className="gc-button" onClick={start} disabled={starting}><Camera size={16}/> {camera.status==='error'?'Try again':'Start camera'}</button></div>}{live&&calibrating&&<div className="gc-cal-target" style={{left:`${CAL_POINTS[calPoint].x*100}%`,top:`${CAL_POINTS[calPoint].y*100}%`}}><Crosshair size={42}/></div>}<div className="gc-camera-readout"><span><i/> {live?`${camera.metrics.handCount} HAND${camera.metrics.handCount===1?'':'S'} TRACKED`:'CAMERA OFFLINE'}</span><span>{current&&current.id!=='unknown'?`${current.name.toUpperCase()} · ${current.confidence}%`:'WAITING FOR GESTURE'}</span></div></div><div className="gc-camera-foot"><span><Aperture size={16}/> {camera.metrics.inferenceMs||'—'} ms inference</span><span><ShieldCheck size={16}/> On-device processing</span></div></section>
        <section className="gc-control-column"><div className="gc-control-card"><div className="gc-control-header"><span className="gc-icon-box"><MousePointer2 size={22}/></span><span className={`gc-state-dot ${desktop.armed?'on':''}`}/></div><h2>System control</h2><p>{desktop.armed?'Gestures are sending mouse and keyboard input.':'Your computer is protected until you arm control.'}</p><button className={`gc-arm-button ${desktop.armed?'pause':''}`} disabled={!live||!desktop.ready} onClick={()=>void arm()}>{desktop.armed?<><Pause size={19}/>Pause control</>:<><Play size={19}/>Arm system control</>}</button><div className="gc-control-hint"><LockKeyhole size={15}/>{!window.gestureDesktop?'Desktop app required for real actions':!desktop.ready?'Input bridge unavailable':!live?'Start the camera to unlock':'Fist freezes the pointer · tray menu can pause'}</div></div>
          <div className="gc-metric-row"><div className="gc-metric"><span>ACTIVE GESTURE</span><strong>{current&&current.id!=='unknown'?current.name:'None detected'}</strong><small>{current&&current.id!=='unknown'?`${current.confidence}% estimated match`:'Show a hand to the camera'}</small></div><div className="gc-metric"><span>MAPPED ACTION</span><strong>{current&&current.id!=='unknown'?actionName(mappings[current.id]??'none'):'—'}</strong><small>{desktop.armed?'Ready to trigger':'Control paused'}</small></div></div>
          <div className="gc-card gc-quick"><div className="gc-card-head"><strong>Quick actions</strong><SlidersHorizontal size={17}/></div><button onClick={()=>setTab('actions')}><Command size={17}/>Edit gesture mappings<span>→</span></button><button onClick={()=>setTab('calibration')}><Crosshair size={17}/>Run 5-point calibration<span>→</span></button><button onClick={()=>setTab('history')}><History size={17}/>View activity log<span>→</span></button></div></section></div>
        <RuntimeWorkspace state={runtime} armed={previewArmed} onArm={()=>setPreviewArmed(value=>!value)} onAction={executePreview}/>
        <div className="gc-bottom-grid"><section className="gc-card gc-recent"><div className="gc-section-head"><h2>Recent activity</h2><button onClick={()=>setTab('history')}>View all →</button></div>{logs.length?logs.slice(0,4).map(item=><div className="gc-log-row" key={item.id}><span className="gc-log-icon"><Hand size={17}/></span><div><strong>{item.gesture}</strong><small>{item.action} · {item.result}</small></div><time>{formatTime(item.time)}</time></div>):<div className="gc-empty-small">No gestures yet. Start the camera and hold a pose.</div>}</section><section className="gc-card gc-overview"><div className="gc-section-head"><h2>Session overview</h2><Activity size={17}/></div><div className="gc-overview-stats"><div><strong>{logs.length}</strong><span>detections logged</span></div><div><strong>{camera.metrics.fps}</strong><span>camera FPS</span></div><div><strong>{profiles.length}</strong><span>custom gestures</span></div></div><div className="gc-progress"><span>Recognition threshold</span><strong>{preferences.threshold}%</strong><div><i style={{width:`${preferences.threshold}%`}}/></div></div></section></div></div>
      {tab==='actions'&&<><div className="gc-info-card"><WandSparkles size={20}/><div><strong>How mappings work</strong><p>Hold a recognized pose for three distinct camera frames. One action fires per hold; change pose or remove your hand to trigger it again. Open Hand moves the pointer when preview or desktop control is armed. Use Try to execute an action in the test workspace.</p></div></div><div className="gc-mapping-table"><div className="gc-table-head"><span>GESTURE</span><span>RECOGNITION</span><span>ASSIGNED ACTION</span><span>TEST ACTION</span></div>{GESTURES.map(g=><div className="gc-mapping-row" key={g.id}><div className="gc-gesture-name"><span>{g.emoji}</span><div><strong>{g.name}</strong><small>{g.description}</small></div></div><span className="gc-chip">Built-in pose</span><select value={mappings[g.id]??'none'} onChange={e=>setMappings(current=>({...current,[g.id]:e.target.value as DesktopAction}))} aria-label={`${g.name} action`}>{ACTIONS.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select><button className="gc-try-button" onClick={()=>tryAction(mappings[g.id]??'none')}>Try →</button></div>)}{profiles.map(p=><div className="gc-mapping-row" key={p.id}><div className="gc-gesture-name"><span>✨</span><div><strong>{p.name}</strong><small>Captured custom pose</small></div></div><span className="gc-chip custom">Custom pose</span><select value={mappings[p.id]??'none'} onChange={e=>setMappings(current=>({...current,[p.id]:e.target.value as DesktopAction}))} aria-label={`${p.name} action`}>{ACTIONS.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select><button className="gc-try-button" onClick={()=>tryAction(mappings[p.id]??'none')}>Try →</button></div>)}</div><div className="gc-info-card muted"><ShieldCheck size={18}/><p>Only allowlisted system actions are available. Arbitrary shell commands and scripts are intentionally not exposed in this version.</p></div></>}
      {tab==='calibration'&&<div className="gc-two-col"><section className="gc-card gc-calibration"><div className="gc-section-head"><h2>Five-point calibration</h2><span className={calibrated?'gc-ready':'gc-chip'}>{calibrated?'● Completed':'Not calibrated'}</span></div><p>Move your palm to each target in the camera view. Hold it steady until the target advances.</p><div className="gc-cal-grid">{CAL_POINTS.map((point,index)=><div key={point.label} className={index<calPoint||calibrated?'done':index===calPoint&&calibrating?'current':''}><span>{index<calPoint||calibrated?<Check size={18}/>:index+1}</span><strong>{point.label}</strong></div>)}</div><button className="gc-button" disabled={!live} onClick={()=>{setCalibrating(true);setCalPoint(0);setTab('control');calibrationHold.current=0}}><Crosshair size={16}/>{calibrating?'Restart calibration':calibrated?'Recalibrate':'Begin calibration'}</button>{!live&&<small>Start the camera before calibrating.</small>}</section><section className="gc-card gc-calibration"><h2>Environment check</h2><div className="gc-check"><span><Camera size={18}/>Camera</span><strong>{live?'Connected':'Not connected'}</strong></div><div className="gc-check"><span><Hand size={18}/>Hands in frame</span><strong>{camera.metrics.handCount}</strong></div><div className="gc-check"><span><Activity size={18}/>Inference speed</span><strong>{camera.metrics.inferenceMs||'—'} ms</strong></div><div className="gc-check"><span><Crosshair size={18}/>Current pose confidence</span><strong>{current?.confidence??'—'}{current?'%':''}</strong></div><p className="gc-help">Use even lighting, keep your entire hand visible, and avoid a busy background. Calibration checks reach and stability; the model itself is not retrained.</p></section></div>}
      {tab==='gestures'&&<><div className="gc-section-head"><h2>Built-in gestures</h2><span>{GESTURES.length} trained geometric poses</span></div><div className="gc-gesture-grid">{GESTURES.map(g=><div className="gc-gesture-card" key={g.id}><span>{g.emoji}</span><strong>{g.name}</strong><small>{g.description}</small><em>{actionName(mappings[g.id]??'none')}</em></div>)}</div><div className="gc-two-col gc-custom-section"><section className="gc-card"><h2>Record a custom pose</h2><p>Hold a distinctive pose in view, enter a name, and capture its 15 landmark descriptors. The camera will recognize similar poses later.</p><div className="gc-field"><label htmlFor="profile-name">GESTURE NAME</label><input id="profile-name" placeholder="e.g. Presentation next" value={profileName} onChange={e=>setProfileName(e.target.value)} maxLength={32}/></div><button className="gc-button" disabled={!live||!profileName.trim()} onClick={captureProfile}><Plus size={17}/>Capture current pose</button></section><section className="gc-card"><h2>Your custom gestures</h2>{profiles.length?profiles.map(p=><div className="gc-custom-row" key={p.id}><span>✨</span><div><strong>{p.name}</strong><small>Created {new Date(p.createdAt).toLocaleDateString()}</small></div><button aria-label={`Delete ${p.name}`} onClick={()=>setProfiles(items=>items.filter(item=>item.id!==p.id))}><Trash2 size={16}/></button></div>):<div className="gc-empty-small">No custom poses yet. Capture one using the live camera.</div>}</section></div></>}
      {tab==='history'&&<section className="gc-card gc-history"><div className="gc-section-head"><h2>Action history</h2><div><button onClick={exportData}><ArrowDownToLine size={15}/> Export JSON</button><button onClick={()=>setLogs([])} disabled={!logs.length}><Trash2 size={15}/> Clear</button></div></div><div className="gc-history-head"><span>TIME</span><span>GESTURE</span><span>CONFIDENCE</span><span>ACTION</span><span>RESULT</span></div>{logs.length?logs.map(item=><div className="gc-history-row" key={item.id}><span>{new Date(item.time).toLocaleString()}</span><strong>{item.gesture}</strong><span>{item.confidence}%</span><span>{item.action}</span><span>{item.result}</span></div>):<div className="gc-empty-small">Your recognition events will appear here.</div>}</section>}
      {tab==='statistics'&&<div className="gc-stats"><div className="gc-stat-card"><span>TOTAL RECOGNITIONS</span><strong>{logs.length}</strong><small>Saved locally on this device</small></div><div className="gc-stat-card"><span>ACTIONS SENT</span><strong>{logs.filter(l=>l.result==='Action sent').length}</strong><small>While control was armed</small></div><div className="gc-stat-card"><span>AVERAGE MATCH</span><strong>{logs.length?Math.round(logs.reduce((sum,l)=>sum+l.confidence,0)/logs.length):0}%</strong><small>Estimated pose-match score</small></div><section className="gc-card gc-frequency"><h2>Gesture frequency</h2>{GESTURES.map(g=>{const count=logs.filter(l=>l.gesture===g.name).length;return <div className="gc-frequency-row" key={g.id}><span>{g.emoji} {g.name}</span><div><i style={{width:`${logs.length?count/logs.length*100:0}%`}}/></div><strong>{count}</strong></div>})}</section></div>}
      {tab==='settings'&&<div className="gc-settings-grid"><section className="gc-card"><h2><ScanLine size={20}/>Recognition</h2><Slider label="Confidence threshold" value={preferences.threshold} min={40} max={95} suffix="%" onChange={n=>updatePreferences('threshold',n)}/><div className="gc-setting-row"><div><strong>Two-hand tracking</strong><small>May lower FPS on slower devices</small></div><input type="checkbox" checked={preferences.hands===2} onChange={e=>{updatePreferences('hands',e.target.checked?2:1);if(live)void camera.start(e.target.checked?2:1)}}/></div><div className="gc-setting-row"><div><strong>Skeleton overlay</strong><small>Show landmark joints over the feed</small></div><input type="checkbox" checked={preferences.skeleton} onChange={e=>updatePreferences('skeleton',e.target.checked)}/></div><div className="gc-setting-row"><div><strong>Mirror camera</strong><small>Match on-screen motion to your hand</small></div><input type="checkbox" checked={preferences.mirror} onChange={e=>updatePreferences('mirror',e.target.checked)}/></div></section><section className="gc-card"><h2><MousePointer2 size={20}/>Pointer & safety</h2><Slider label="Cursor smoothing" value={preferences.smoothing} min={0} max={95} suffix="%" onChange={n=>updatePreferences('smoothing',n)}/><Slider label="Action cooldown" value={preferences.cooldown} min={300} max={1500} step={50} suffix=" ms" onChange={n=>updatePreferences('cooldown',n)}/><Slider label="No-hand timeout" value={preferences.inactivity} min={30} max={300} step={10} suffix=" sec" onChange={n=>updatePreferences('inactivity',n)}/><div className="gc-setting-row"><div><strong>Action sound</strong><small>Play a short tone on recognition</small></div><input type="checkbox" checked={preferences.sound} onChange={e=>updatePreferences('sound',e.target.checked)}/></div></section><section className="gc-card"><h2><ArrowDownToLine size={20}/>Profiles & data</h2><p>Export mappings, custom poses, settings and history as JSON. Import reviews only the mapped actions and custom poses.</p><div className="gc-import-actions"><button className="gc-button secondary" onClick={exportData}>Export profile</button><label className="gc-button secondary">Import profile<input type="file" accept="application/json,.json" onChange={e=>{const file=e.target.files?.[0];if(file)importData(file);e.target.value=''}} hidden/></label></div></section><section className="gc-card"><h2><ShieldCheck size={20}/>System access</h2><div className="gc-check"><span>Desktop bridge</span><strong>{desktop.ready?'Ready':window.gestureDesktop?'Unavailable':'Browser only'}</strong></div><div className="gc-check"><span>Control state</span><strong>{desktop.armed?'Armed':'Paused'}</strong></div><p className="gc-help">All frames and landmarks stay on this device. System input is blocked by default, and pausing is always available in the app or tray.</p></section></div>}
      </main></div>
    {toast&&<div className="gc-toast" role="status"><Check size={17}/>{toast}</div>}
    {showGuide&&<div className="gc-modal-backdrop" onMouseDown={()=>setShowGuide(false)}><div className="gc-modal" role="dialog" aria-modal="true" aria-label="How GestureCommand works" onMouseDown={e=>e.stopPropagation()}><button className="gc-modal-close" onClick={()=>setShowGuide(false)}>×</button><div className="gc-logo-icon"><Hand size={23}/></div><h2>Control starts with consent.</h2><p>1. Start the camera and allow permission. Hand landmarks are processed locally.</p><p>2. Set mappings, then launch the desktop app to enable real system actions.</p><p>3. Arm control only when ready. Open Hand moves the pointer; Fist stops movement. Pause, minimize or use the tray to stop.</p><p>Custom poses can be captured in the Gesture library. The current build does not yet support swipes, drag-and-drop, arbitrary commands or cloud sync.</p><button className="gc-button" onClick={()=>setShowGuide(false)}>Got it</button></div></div>}
  </div>
}

function Slider({label,value,min,max,step=1,suffix,onChange}:{label:string;value:number;min:number;max:number;step?:number;suffix:string;onChange:(value:number)=>void}){
  return <label className="gc-slider"><span><strong>{label}</strong><em>{value}{suffix}</em></span><input type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>
}
